# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: scrapxchangedb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 2706
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
  
#   backend:
#     build: 
#       context: .
#     volumes:
#       - .:/usr/src/app
#     ports:
#       - "8000:8000"
#     environment:
#       POSTGRES_DB: scrapxchangedb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 2706
#       POSTGRES_HOST: db
#     depends_on:
#       - db
    
# volumes:
#   postgres_data: