# Generated by Django 5.0.7 on 2024-09-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapxchange_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
