# Generated by Django 5.0.7 on 2024-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapxchange_admin', '0002_report_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fraud', 'Fraud'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('other', 'Other')], max_length=20),
        ),
    ]
