# Generated by Django 5.0.7 on 2024-08-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
