# Generated by Django 5.0.7 on 2024-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='profile_picture',
            field=models.CharField(blank=True),
        ),
    ]
