# Generated by Django 5.0.7 on 2024-10-28 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chatroom_collectionrequest_message_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
