# Generated by Django 5.0.7 on 2024-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_collectionrequest_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='reject_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
