# Generated by Django 5.0.7 on 2024-11-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_collectionrequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=100),
        ),
    ]
