# Generated by Django 5.0.7 on 2024-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
