# Generated by Django 5.0.7 on 2024-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_transaction_transactionproduct_transaction_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
