# Generated by Django 5.0.7 on 2024-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_message_audio_alter_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
