# Generated by Django 5.0.7 on 2024-08-27 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_transaction_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
