# Generated by Django 5.0.7 on 2024-08-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_transaction_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upi_id',
        ),
    ]
