# Generated by Django 5.0.7 on 2024-08-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_transaction_upi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='payment_id',
        ),
    ]
