# Generated by Django 5.0.7 on 2024-08-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_transaction_id_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='is_collected',
            field=models.BooleanField(default=True),
        ),
    ]
