# Generated by Django 5.0.7 on 2024-09-11 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_message_audio_message_video_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='add_note',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
