# Generated by Django 5.0.7 on 2024-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_userprofile_warning_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('report', 'Report')], default='general', max_length=20),
        ),
    ]
